//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS_Repayment
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveContractInfoRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class RetrieveContractInfoRequest : object
    {
        
        private string authen_keyField;
        
        private string contractNumberField;
        
        private string partnerCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authen_key
        {
            get
            {
                return this.authen_keyField;
            }
            set
            {
                this.authen_keyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetrieveContractInfoResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class RetrieveContractInfoResponse : object
    {
        
        private string clientFullNameField;
        
        private string clientIDNumberField;
        
        private string contractNumberField;
        
        private string dueDateField;
        
        private string installmentAmountField;
        
        private decimal maximumAmountField;
        
        private int paid_installmentField;
        
        private int resposeCodeField;
        
        private string resposeMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientFullName
        {
            get
            {
                return this.clientFullNameField;
            }
            set
            {
                this.clientFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientIDNumber
        {
            get
            {
                return this.clientIDNumberField;
            }
            set
            {
                this.clientIDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dueDate
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string installmentAmount
        {
            get
            {
                return this.installmentAmountField;
            }
            set
            {
                this.installmentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal maximumAmount
        {
            get
            {
                return this.maximumAmountField;
            }
            set
            {
                this.maximumAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paid_installment
        {
            get
            {
                return this.paid_installmentField;
            }
            set
            {
                this.paid_installmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int resposeCode
        {
            get
            {
                return this.resposeCodeField;
            }
            set
            {
                this.resposeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resposeMessage
        {
            get
            {
                return this.resposeMessageField;
            }
            set
            {
                this.resposeMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultRequest : object
    {
        
        private string authenKeyField;
        
        private string partnerCodeField;
        
        private PCS_Repayment.PaymentResultRequestDetails[] paymentResultRequestDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authenKey
        {
            get
            {
                return this.authenKeyField;
            }
            set
            {
                this.authenKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCS_Repayment.PaymentResultRequestDetails[] paymentResultRequestDetails
        {
            get
            {
                return this.paymentResultRequestDetailsField;
            }
            set
            {
                this.paymentResultRequestDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultRequestDetails", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultRequestDetails : object
    {
        
        private string clientPhoneField;
        
        private string contractNumberField;
        
        private decimal moneyAmountField;
        
        private string noteField;
        
        private System.Nullable<System.DateTime> paymentCancelledDateField;
        
        private System.DateTime paymentDateField;
        
        private string paymentIdField;
        
        private int paymentStatusField;
        
        private string postCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientPhone
        {
            get
            {
                return this.clientPhoneField;
            }
            set
            {
                this.clientPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal moneyAmount
        {
            get
            {
                return this.moneyAmountField;
            }
            set
            {
                this.moneyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> paymentCancelledDate
        {
            get
            {
                return this.paymentCancelledDateField;
            }
            set
            {
                this.paymentCancelledDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime paymentDate
        {
            get
            {
                return this.paymentDateField;
            }
            set
            {
                this.paymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultResponse : object
    {
        
        private PCS_Repayment.PaymentResultResponseDetails[] paymentResultResponseDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PCS_Repayment.PaymentResultResponseDetails[] paymentResultResponseDetails
        {
            get
            {
                return this.paymentResultResponseDetailsField;
            }
            set
            {
                this.paymentResultResponseDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultResponseDetails", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultResponseDetails : object
    {
        
        private string paymentIdField;
        
        private int responseCodeField;
        
        private string responseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultOneRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultOneRequest : object
    {
        
        private string authenKeyField;
        
        private string clientPhoneField;
        
        private string contractNumberField;
        
        private decimal moneyAmountField;
        
        private string noteField;
        
        private string partnerCodeField;
        
        private System.Nullable<System.DateTime> paymentCancelledDateField;
        
        private System.DateTime paymentDateField;
        
        private string paymentIdField;
        
        private int paymentStatusField;
        
        private string postCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string authenKey
        {
            get
            {
                return this.authenKeyField;
            }
            set
            {
                this.authenKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clientPhone
        {
            get
            {
                return this.clientPhoneField;
            }
            set
            {
                this.clientPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contractNumber
        {
            get
            {
                return this.contractNumberField;
            }
            set
            {
                this.contractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal moneyAmount
        {
            get
            {
                return this.moneyAmountField;
            }
            set
            {
                this.moneyAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> paymentCancelledDate
        {
            get
            {
                return this.paymentCancelledDateField;
            }
            set
            {
                this.paymentCancelledDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime paymentDate
        {
            get
            {
                return this.paymentDateField;
            }
            set
            {
                this.paymentDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int paymentStatus
        {
            get
            {
                return this.paymentStatusField;
            }
            set
            {
                this.paymentStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postCode
        {
            get
            {
                return this.postCodeField;
            }
            set
            {
                this.postCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResultOneResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class PaymentResultOneResponse : object
    {
        
        private string paymentIdField;
        
        private int responseCodeField;
        
        private string responseMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string paymentId
        {
            get
            {
                return this.paymentIdField;
            }
            set
            {
                this.paymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int responseCode
        {
            get
            {
                return this.responseCodeField;
            }
            set
            {
                this.responseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseMessage
        {
            get
            {
                return this.responseMessageField;
            }
            set
            {
                this.responseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContractRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class GetContractRequest : object
    {
        
        private System.Nullable<int> combineTypeField;
        
        private byte[] encryptedField;
        
        private string partnerCodeField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> combineType
        {
            get
            {
                return this.combineTypeField;
            }
            set
            {
                this.combineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContractResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class GetContractResponse : object
    {
        
        private byte[] encryptedField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPaymentResultRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class SendPaymentResultRequest : object
    {
        
        private System.Nullable<int> combineTypeField;
        
        private byte[] encryptedField;
        
        private string partnerCodeField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> combineType
        {
            get
            {
                return this.combineTypeField;
            }
            set
            {
                this.combineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendPaymentResultResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class SendPaymentResultResponse : object
    {
        
        private byte[] encryptedField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://homecredit.net/pcs/ws/paymentChannel", ConfigurationName="PCS_Repayment.IPaymentChannelWS")]
    public interface IPaymentChannelWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/RetrieveContractInf" +
            "o", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/RetrieveContractInf" +
            "oResponse")]
        PCS_Repayment.RetrieveContractInfoResponse RetrieveContractInfo(PCS_Repayment.RetrieveContractInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/RetrieveContractInf" +
            "o", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/RetrieveContractInf" +
            "oResponse")]
        System.Threading.Tasks.Task<PCS_Repayment.RetrieveContractInfoResponse> RetrieveContractInfoAsync(PCS_Repayment.RetrieveContractInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResult", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultRe" +
            "sponse")]
        PCS_Repayment.PaymentResultResponse SendPaymentResult(PCS_Repayment.PaymentResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResult", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultRe" +
            "sponse")]
        System.Threading.Tasks.Task<PCS_Repayment.PaymentResultResponse> SendPaymentResultAsync(PCS_Repayment.PaymentResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultOn" +
            "e", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultOn" +
            "eResponse")]
        PCS_Repayment.PaymentResultOneResponse SendPaymentResultOne(PCS_Repayment.PaymentResultOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultOn" +
            "e", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultOn" +
            "eResponse")]
        System.Threading.Tasks.Task<PCS_Repayment.PaymentResultOneResponse> SendPaymentResultOneAsync(PCS_Repayment.PaymentResultOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/GetContractEncrypt", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/GetContractEncryptR" +
            "esponse")]
        PCS_Repayment.GetContractResponse GetContractEncrypt(PCS_Repayment.GetContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/GetContractEncrypt", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/GetContractEncryptR" +
            "esponse")]
        System.Threading.Tasks.Task<PCS_Repayment.GetContractResponse> GetContractEncryptAsync(PCS_Repayment.GetContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultEn" +
            "crypt", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultEn" +
            "cryptResponse")]
        PCS_Repayment.SendPaymentResultResponse SendPaymentResultEncrypt(PCS_Repayment.SendPaymentResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultEn" +
            "crypt", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IPaymentChannelWS/SendPaymentResultEn" +
            "cryptResponse")]
        System.Threading.Tasks.Task<PCS_Repayment.SendPaymentResultResponse> SendPaymentResultEncryptAsync(PCS_Repayment.SendPaymentResultRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPaymentChannelWSChannel : PCS_Repayment.IPaymentChannelWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PaymentChannelWSClient : System.ServiceModel.ClientBase<PCS_Repayment.IPaymentChannelWS>, PCS_Repayment.IPaymentChannelWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaymentChannelWSClient() : 
                base(PaymentChannelWSClient.GetDefaultBinding(), PaymentChannelWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPaymentChannelWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentChannelWSClient(EndpointConfiguration endpointConfiguration) : 
                base(PaymentChannelWSClient.GetBindingForEndpoint(endpointConfiguration), PaymentChannelWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentChannelWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaymentChannelWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentChannelWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaymentChannelWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaymentChannelWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PCS_Repayment.RetrieveContractInfoResponse RetrieveContractInfo(PCS_Repayment.RetrieveContractInfoRequest request)
        {
            return base.Channel.RetrieveContractInfo(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Repayment.RetrieveContractInfoResponse> RetrieveContractInfoAsync(PCS_Repayment.RetrieveContractInfoRequest request)
        {
            return base.Channel.RetrieveContractInfoAsync(request);
        }
        
        public PCS_Repayment.PaymentResultResponse SendPaymentResult(PCS_Repayment.PaymentResultRequest request)
        {
            return base.Channel.SendPaymentResult(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Repayment.PaymentResultResponse> SendPaymentResultAsync(PCS_Repayment.PaymentResultRequest request)
        {
            return base.Channel.SendPaymentResultAsync(request);
        }
        
        public PCS_Repayment.PaymentResultOneResponse SendPaymentResultOne(PCS_Repayment.PaymentResultOneRequest request)
        {
            return base.Channel.SendPaymentResultOne(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Repayment.PaymentResultOneResponse> SendPaymentResultOneAsync(PCS_Repayment.PaymentResultOneRequest request)
        {
            return base.Channel.SendPaymentResultOneAsync(request);
        }
        
        public PCS_Repayment.GetContractResponse GetContractEncrypt(PCS_Repayment.GetContractRequest request)
        {
            return base.Channel.GetContractEncrypt(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Repayment.GetContractResponse> GetContractEncryptAsync(PCS_Repayment.GetContractRequest request)
        {
            return base.Channel.GetContractEncryptAsync(request);
        }
        
        public PCS_Repayment.SendPaymentResultResponse SendPaymentResultEncrypt(PCS_Repayment.SendPaymentResultRequest request)
        {
            return base.Channel.SendPaymentResultEncrypt(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Repayment.SendPaymentResultResponse> SendPaymentResultEncryptAsync(PCS_Repayment.SendPaymentResultRequest request)
        {
            return base.Channel.SendPaymentResultEncryptAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaymentChannelWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPaymentChannelWS))
            {
                return new System.ServiceModel.EndpointAddress("http://pcs.homecredit.vn/PaymentChannelWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaymentChannelWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPaymentChannelWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaymentChannelWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPaymentChannelWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPaymentChannelWS,
        }
    }
}
