//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCS_Disbursement
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyContractRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class VerifyContractRequest : object
    {
        
        private System.Nullable<int> combineTypeField;
        
        private byte[] encryptedField;
        
        private string partnerCodeField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> combineType
        {
            get
            {
                return this.combineTypeField;
            }
            set
            {
                this.combineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerifyContractResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class VerifyContractResponse : object
    {
        
        private byte[] encryptedField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisburseContractRequest", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class DisburseContractRequest : object
    {
        
        private System.Nullable<int> combineTypeField;
        
        private byte[] encryptedField;
        
        private string partnerCodeField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> combineType
        {
            get
            {
                return this.combineTypeField;
            }
            set
            {
                this.combineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisburseContractResponse", Namespace="http://schemas.datacontract.org/2004/07/HCVN.PaymentChannel.Core.Model")]
    public partial class DisburseContractResponse : object
    {
        
        private byte[] encryptedField;
        
        private byte[] signatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] encrypted
        {
            get
            {
                return this.encryptedField;
            }
            set
            {
                this.encryptedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://homecredit.net/pcs/ws/paymentChannel", ConfigurationName="PCS_Disbursement.IDisbursementChannelWS")]
    public interface IDisbursementChannelWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/VerifyContract" +
            "", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/VerifyContract" +
            "Response")]
        PCS_Disbursement.VerifyContractResponse VerifyContract(PCS_Disbursement.VerifyContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/VerifyContract" +
            "", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/VerifyContract" +
            "Response")]
        System.Threading.Tasks.Task<PCS_Disbursement.VerifyContractResponse> VerifyContractAsync(PCS_Disbursement.VerifyContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/DisburseContra" +
            "ct", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/DisburseContra" +
            "ctResponse")]
        PCS_Disbursement.DisburseContractResponse DisburseContract(PCS_Disbursement.DisburseContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/DisburseContra" +
            "ct", ReplyAction="http://homecredit.net/pcs/ws/paymentChannel/IDisbursementChannelWS/DisburseContra" +
            "ctResponse")]
        System.Threading.Tasks.Task<PCS_Disbursement.DisburseContractResponse> DisburseContractAsync(PCS_Disbursement.DisburseContractRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDisbursementChannelWSChannel : PCS_Disbursement.IDisbursementChannelWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DisbursementChannelWSClient : System.ServiceModel.ClientBase<PCS_Disbursement.IDisbursementChannelWS>, PCS_Disbursement.IDisbursementChannelWS
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DisbursementChannelWSClient() : 
                base(DisbursementChannelWSClient.GetDefaultBinding(), DisbursementChannelWSClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDisbursementChannelWS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisbursementChannelWSClient(EndpointConfiguration endpointConfiguration) : 
                base(DisbursementChannelWSClient.GetBindingForEndpoint(endpointConfiguration), DisbursementChannelWSClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisbursementChannelWSClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DisbursementChannelWSClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisbursementChannelWSClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DisbursementChannelWSClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisbursementChannelWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public PCS_Disbursement.VerifyContractResponse VerifyContract(PCS_Disbursement.VerifyContractRequest request)
        {
            return base.Channel.VerifyContract(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Disbursement.VerifyContractResponse> VerifyContractAsync(PCS_Disbursement.VerifyContractRequest request)
        {
            return base.Channel.VerifyContractAsync(request);
        }
        
        public PCS_Disbursement.DisburseContractResponse DisburseContract(PCS_Disbursement.DisburseContractRequest request)
        {
            return base.Channel.DisburseContract(request);
        }
        
        public System.Threading.Tasks.Task<PCS_Disbursement.DisburseContractResponse> DisburseContractAsync(PCS_Disbursement.DisburseContractRequest request)
        {
            return base.Channel.DisburseContractAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDisbursementChannelWS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDisbursementChannelWS))
            {
                return new System.ServiceModel.EndpointAddress("http://pcs.homecredit.vn/DisbursementChannelWS.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DisbursementChannelWSClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDisbursementChannelWS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DisbursementChannelWSClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDisbursementChannelWS);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDisbursementChannelWS,
        }
    }
}
